name: Terraform EKS Deployment

on:
  workflow_dispatch:
    inputs:
      tf-action:
        description: 'Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - plan
          - destroy

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: "github-actions-eks"
  TF_VERSION: "1.6.6"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: .

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: .

    - name: Terraform Plan
      id: plan
      if: github.event.inputs.tf-action == 'plan' || github.event.inputs.tf-action == 'apply'
      run: terraform plan -var="cluster_name=${{ env.CLUSTER_NAME }}" -input=false
      working-directory: .

    - name: Terraform Apply
      id: apply
      if: github.event.inputs.tf-action == 'apply'
      run: terraform apply -auto-approve -var="cluster_name=${{ env.CLUSTER_NAME }}"
      working-directory: .

    - name: Terraform Destroy
      id: destroy
      if: github.event.inputs.tf-action == 'destroy'
      run: terraform destroy -auto-approve -var="cluster_name=${{ env.CLUSTER_NAME }}"
      working-directory: .

    - name: Configure kubectl
      if: github.event.inputs.tf-action == 'apply' && steps.apply.outcome == 'success'
      run: |
        aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}
        kubectl get nodes

    - name: Upload kubeconfig
      if: github.event.inputs.tf-action == 'apply' && steps.apply.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: kubeconfig
        path: |
          ~/.kube/config
          terraform.tfstate